name: build-delpoy-actions
run-name: build-delpoy-actions
on: 
  workflow_dispatch:
jobs:
  CloudFormation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: msgolf-hp-resources
          template: template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            SSRFunctionDomainName=${{ secrets.SSRFunctionDomainName }},
            AcmId=${{ secrets.AcmId }}
